name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
concurrency: group:${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}

jobs:
  sub_job_skipped:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Run sub workflow script
        run: echo "Running sub workflow script"
  sub_job_failed:
    runs-on: ubuntu-latest
    steps:
      - name: Run sub workflow script
        run: |
          exit 1
  sub_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run sub workflow script
        run: echo "Running sub workflow script"
  
  all_pre_jobs_build:
    needs: [sub_job, sub_job_failed, sub_job_skipped]
    permissions:
      contents: read # Allows the job to read & checkout the contents of the repository
      actions: read # Allows the job to read the status of other actions
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "Running fine"
  
  all_pre_jobs_build_success:
    if: ${{ success() }}
    needs: [sub_job, sub_job_failed, sub_job_skipped]
    permissions:
      contents: read # Allows the job to read & checkout the contents of the repository
      actions: read # Allows the job to read the status of other actions
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "Running fine"
  
  all_pre_jobs_build_not_cancelled:
    needs: [sub_job, sub_job_failed, sub_job_skipped]
    permissions:
      contents: read # Allows the job to read & checkout the contents of the repository
      actions: read # Allows the job to read the status of other actions
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Run build script
        run: echo "Running fine"
  
  all_pre_jobs_build_not_cancelled_not_failure:
    needs: [sub_job, sub_job_failed, sub_job_skipped]
    permissions:
      contents: read # Allows the job to read & checkout the contents of the repository
      actions: read # Allows the job to read the status of other actions
    runs-on: ubuntu-latest
    if: ${{ !cancelled() && !failure() }}
    steps:
      - name: Run build script
        run: echo "Running fine"

  not_failure_job_build:
    needs: [sub_job, sub_job_failed, sub_job_skipped]
    permissions:
      contents: read # Allows the job to read & checkout the contents of the repository
      actions: read # Allows the job to read the status of other actions
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "Running fine"
  
  not_failure_job_build_success:
    if: ${{ success() }}
    needs: [sub_job, sub_job_failed, sub_job_skipped]
    permissions:
      contents: read # Allows the job to read & checkout the contents of the repository
      actions: read # Allows the job to read the status of other actions
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "Running fine"
  
  not_failure_job_build_not_cancelled:
    needs: [sub_job, sub_job_failed, sub_job_skipped]
    permissions:
      contents: read # Allows the job to read & checkout the contents of the repository
      actions: read # Allows the job to read the status of other actions
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Run build script
        run: echo "Running fine"
  
  not_failure_job_build_not_cancelled_not_failure:
    needs: [sub_job, sub_job_failed, sub_job_skipped]
    permissions:
      contents: read # Allows the job to read & checkout the contents of the repository
      actions: read # Allows the job to read the status of other actions
    runs-on: ubuntu-latest
    if: ${{ !cancelled() && !failure() }}
    steps:
      - name: Run build script
        run: echo "Running fine"


