name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
concurrency: group:${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}

jobs:
  make_success:
    runs-on: ubuntu-latest
    steps:
      - name: Run success script
        run: echo "Running success script"
  sub_job:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Run sub workflow script
        run: echo "Running sub workflow script"
  build:
    needs: [sub_job,]
    permissions:
      contents: read # Allows the job to read & checkout the contents of the repository
      actions: read # Allows the job to read the status of other actions
    if: ${{ github.event_name == 'pull_request' && !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "Running fine"
