name: Sub Workflow
on:
  workflow_call:
    inputs: 
      run_job:
        description: 'Input 1'
        default: true
        type: boolean

jobs:
  sub_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_job}}
    steps:
      - name: Run sub workflow script
        run: echo "Running sub workflow script"